# How to use an API with Python

The Python language has a couple of add-on libraries that can help us send API calls and make sense of the responses. The first library is called **requests**. 

If you don't have Python installed on your computer, or you're not able to add the required libraries, you can use this online Python notebook to see how the calls would work. Each cell of the notebook contains a bit of Python code, and you run the code by selecting the cell and pressing Shift+Enter at the same time.

In [19]:
import requests
response = requests.get("http://api.open-notify.org/iss-now.json")
print (response.status_code)

200

#### Error codes:
**200** = means 'OK'<br>
**400** means it's a 'bad request' - the server can't work out what you mean (possibly because you need to add some parameters)<br>
**404** means 'not found' - there's nothing at the url you've specified.

In [21]:
response = requests.get("http://api.open-notify.org/iss-pass.json")
print (response.status_code)

400

In [22]:
response = requests.get("http://api.open-notify.org/iss-pass.json?lat=40.71&lon=-74")
print (response.status_code)

200

In [23]:
print (response.content)

b'{\n  "message": "success", \n  "request": {\n    "altitude": 100, \n    "datetime": 1505043309, \n    "latitude": 40.71, \n    "longitude": -74.0, \n    "passes": 5\n  }, \n  "response": [\n    {\n      "duration": 634, \n      "risetime": 1505045640\n    }, \n    {\n      "duration": 598, \n      "risetime": 1505051437\n    }, \n    {\n      "duration": 544, \n      "risetime": 1505105668\n    }, \n    {\n      "duration": 643, \n      "risetime": 1505111384\n    }, \n    {\n      "duration": 582, \n      "risetime": 1505117232\n    }\n  ]\n}\n'

In [26]:
response = requests.get("http://api.open-notify.org/astros.json")
print (response.content)

b'{"message": "success", "people": [{"name": "Sergey Ryazanskiy", "craft": "ISS"}, {"name": "Randy Bresnik", "craft": "ISS"}, {"name": "Paolo Nespoli", "craft": "ISS"}], "number": 3}'

The other useful Python library is called **pandas**; this lets us define and view raw data as a table, like a spreadsheet. We can use the read_csv and DataFrame functions to get the data and structure it into a tabular view.

You can use pandas to read in other data formats, like json, but it's easiest to do the basic operations on csv and similarly-structured text files.

In [30]:
import pandas as pd
data = pd.read_csv("https://country.register.gov.uk/records.csv")
df = pd.DataFrame(data)
df

,index-entry-number,entry-number,entry-timestamp,key,country,name,official-name,citizen-names,start-date,end-date
0,206,206,2017-03-29T14:22:30Z,GM,GM,The Gambia,The Republic of The Gambia,Gambian,NaN,NaN
1,205,205,2016-11-11T16:25:07Z,CZ,CZ,Czechia,The Czech Republic,Czech,1993-01-01,NaN
2,204,204,2016-04-05T13:23:05Z,VA,VA,Vatican City,Vatican City State,Vatican citizen,NaN,NaN
3,203,203,2016-04-05T13:23:05Z,BS,BS,The Bahamas,The Commonwealth of The Bahamas,Bahamian,NaN,NaN
4,200,200,2016-04-05T13:23:05Z,ZW,ZW,Zimbabwe,The Republic of Zimbabwe,Zimbabwean,1980-04-18,NaN
5,199,199,2016-04-05T13:23:05Z,ZM,ZM,Zambia,The Republic of Zambia,Zambian,NaN,NaN
6,198,198,2016-04-05T13:23:05Z,YE,YE,Yemen,The Republic of Yemen,Yemeni,1990-05-22,NaN
7,197,197,2016-04-05T13:23:05Z,VN,VN,Vietnam,The Socialist Republic of Vietnam,Vietnamese,NaN,NaN
8,196,196,2016-04-05T13:23:05Z,VE,VE,Venezuela,The Bolivarian Republic of Venezuela,Venezuelan,NaN,NaN
9,194,194,2016-04-05T13:23:05Z,VU,VU,Vanuatu,The Republic of Vanuatu,Citizen of Vanuatu,1980-07-30,NaN
10,193,193,2016-04-05T13:23:05Z,UZ,UZ,Uzbekistan,The Republic of Uzbekistan,Uzbek,1991-09-01,NaN
11,192,192,2016-04-05T13:23:05Z,UY,UY,Uruguay,The Oriental Republic of Uruguay,Uruguayan,NaN,NaN
12,191,191,2016-04-05T13:23:05Z,US,US,United States,The United States of America,United States citizen,NaN,NaN
13,190,190,2016-04-05T13:23:05Z,AE,AE,United Arab Emirates,The United Arab Emirates,Citizen of the United Arab Emirates,NaN,NaN
14,189,189,2016-04-05T13:23:05Z,UA,UA,Ukraine,Ukraine,Ukrainian,1991-08-24,NaN
15,188,188,2016-04-05T13:23:05Z,UG,UG,Uganda,The Republic of Uganda,Ugandan,NaN,NaN
16,187,187,2016-04-05T13:23:05Z,TV,TV,Tuvalu,Tuvalu,Tuvaluan,1978-10-01,NaN
17,186,186,2016-04-05T13:23:05Z,TM,TM,Turkmenistan,Turkmenistan,Turkmen,1991-10-27,NaN
18,185,185,2016-04-05T13:23:05Z,TR,TR,Turkey,The Republic of Turkey,Turk,NaN,NaN
19,184,184,2016-04-05T13:23:05Z,TN,TN,Tunisia,The Tunisian Republic,Tunisian,NaN,NaN
20,183,183,2016-04-05T13:23:05Z,TT,TT,Trinidad and Tobago,The Republic of Trinidad and Tobago,Trinidad and Tobago citizen,NaN,NaN
21,182,182,2016-04-05T13:23:05Z,TO,TO,Tonga,The Kingdom of Tonga,Tongan,NaN,NaN
22,181,181,2016-04-05T13:23:05Z,TG,TG,Togo,The Togolese Republic,Togolese,NaN,NaN
23,180,180,2016-04-05T13:23:05Z,TH,TH,Thailand,The Kingdom of Thailand,Thai,NaN,NaN
24,179,179,2016-04-05T13:23:05Z,TZ,TZ,Tanzania,The United Republic of Tanzania,Tanzanian,NaN,NaN
25,178,178,2016-04-05T13:23:05Z,TJ,TJ,Tajikistan,The Republic of Tajikistan,Tajik,1991-09-09,NaN
26,177,177,2016-04-05T13:23:05Z,SY,SY,Syria,The Syrian Arab Republic,Syrian,NaN,NaN
27,176,176,2016-04-05T13:23:05Z,CH,CH,Switzerland,The Swiss Confederation,Swiss,NaN,NaN
28,175,175,2016-04-05T13:23:05Z,SE,SE,Sweden,The Kingdom of Sweden,Swede,NaN,NaN
29,174,174,2016-04-05T13:23:05Z,SZ,SZ,Swaziland,The Kingdom of Swaziland,Swazi,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
70,133,133,2016-04-05T13:23:05Z,NZ,NZ,New Zealand,New Zealand,New Zealander,NaN,NaN
71,132,132,2016-04-05T13:23:05Z,NL,NL,Netherlands,The Kingdom of the Netherlands,Dutch citizen;Dutchman;Dutchwoman,NaN,NaN
72,131,131,2016-04-05T13:23:05Z,NP,NP,Nepal,The Federal Democratic Republic of Nepal,Nepalese,NaN,NaN
73,130,130,2016-04-05T13:23:05Z,NR,NR,Nauru,The Republic of Nauru,Nauruan,NaN,NaN
74,129,129,2016-04-05T13:23:05Z,NaN,NaN,Namibia,The Republic of Namibia,Namibian,1980-03-21,NaN
75,128,128,2016-04-05T13:23:05Z,MZ,MZ,Mozambique,The Republic of Mozambique,Mozambican,1975-06-25,NaN
76,127,127,2016-04-05T13:23:05Z,MA,MA,Morocco,The Kingdom of Morocco,Moroccan,NaN,NaN
77,126,126,2016-04-05T13:23:05Z,ME,ME,Montenegro,Montenegro,Montenegrin,NaN,NaN
78,125,125,2016-04-05T13:23:05Z,MN,MN,Mongolia,Mongolia,Mongolian,NaN,NaN
79,124,124,2016-04-05T13:23:05Z,MC,MC,Monaco,The Principality of Monaco,Monegasque,NaN,NaN
80,123,123,2016-04-05T13:23:05Z,MD,MD,Moldova,The Republic of Moldova,Moldovan,1991-08-27,NaN
81,122,122,2016-04-05T13:23:05Z,FM,FM,Micronesia,The Federated States of Micronesia,Micronesian,1986-11-03,NaN
82,121,121,2016-04-05T13:23:05Z,MX,MX,Mexico,The United Mexican States,Mexican,NaN,NaN
83,120,120,2016-04-05T13:23:05Z,MU,MU,Mauritius,The Republic of Mauritius,Mauritian,NaN,NaN
84,119,119,2016-04-05T13:23:05Z,MR,MR,Mauritania,The Islamic Republic of Mauritania,Mauritanian,NaN,NaN
85,118,118,2016-04-05T13:23:05Z,MH,MH,Marshall Islands,The Republic of the Marshall Islands,Marshall Islander,1986-10-21,NaN
86,117,117,2016-04-05T13:23:05Z,MT,MT,Malta,The Republic of Malta,Maltese,NaN,NaN
87,116,116,2016-04-05T13:23:05Z,ML,ML,Mali,The Republic of Mali,Malian,NaN,NaN
88,115,115,2016-04-05T13:23:05Z,MV,MV,Maldives,The Republic of Maldives,Maldivian,NaN,NaN
89,114,114,2016-04-05T13:23:05Z,MY,MY,Malaysia,Malaysia,Citizen of Malaysia,NaN,NaN
90,113,113,2016-04-05T13:23:05Z,MW,MW,Malawi,The Republic of Malawi,Malawian,NaN,NaN
91,112,112,2016-04-05T13:23:05Z,MG,MG,Madagascar,The Republic of Madagascar,Citizen of Madagascar,NaN,NaN
92,111,111,2016-04-05T13:23:05Z,MK,MK,Macedonia,The Republic of Macedonia,Macedonian,1991-09-08,NaN
93,110,110,2016-04-05T13:23:05Z,LU,LU,Luxembourg,The Grand Duchy of Luxembourg,Luxembourger,NaN,NaN
94,109,109,2016-04-05T13:23:05Z,LT,LT,Lithuania,The Republic of Lithuania,Lithuanian,1990-03-11,NaN
95,108,108,2016-04-05T13:23:05Z,LI,LI,Liechtenstein,The Principality of Liechtenstein,Liechtenstein citizen,NaN,NaN
96,107,107,2016-04-05T13:23:05Z,LY,LY,Libya,Libya,Libyan,NaN,NaN
97,106,106,2016-04-05T13:23:05Z,LR,LR,Liberia,The Republic of Liberia,Liberian,NaN,NaN
98,105,105,2016-04-05T13:23:05Z,LS,LS,Lesotho,The Kingdom of Lesotho,Citizen of Lesotho,NaN,NaN
99,104,104,2016-04-05T13:23:05Z,LB,LB,Lebanon,The Lebanese Republic,Lebanese,NaN,NaN